Fix of Fatal Error due previous to interface changes
Fatal error: Class Spy\TimelineBundle\Driver\ODM\Pager contains 4
abstract methods and must therefore be declared abstract or implement
the remaining methods (ArrayAccess::offsetExists,
ArrayAccess::offsetGet, ArrayAccess::offsetSet, ...) in
/var/www/Kolektado/vendor/stephpy/TimelineBundle/Spy/TimelineBundle/Driv
er/ODM/Pager.php on line 113